version: 0.2

env:
  variables:
    # this value can override during manual build for dev, ppe and prod
    STAGE: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
  pre_build:
    commands:
      - mkdir -p artifact
      - npm install
  build:
    commands:
      - npm run build
      - npm prune --production
      - zip -r artifact/luckalot-sanook-api.zip dist/ node_modules
      - aws cloudformation package --template-file template.yaml --s3-bucket luckalot-sanook-api-artifact --output-template-file artifact/template.${STAGE}.out.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file artifact/template.${STAGE}.out.yaml --stack-name luckalot-sanook-api-stack --capabilities CAPABILITY_NAMED_IAM
artifacts:
 files:
  - artifact/template.${STAGE}.out.yaml
 discard-paths: yes