AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: luckalot-sanook-api stack

Parameters:
  AppName:
    Type: String
    Default: luckalot-sanook-api
  StageName:
    Type: String
    Default: dev
    AllowedValues: [dev, ppe, prod]
    ConstraintDescription: must specify dev, ppe or prod

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join ['-', [!Ref AppName, gateway]]
      StageName: api
      EndpointConfiguration: REGIONAL
  ProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [!Ref AppName, proxy-function]]
      Handler: dist/lambda-entry-point.handler
      Runtime: nodejs12.x
      CodeUri: artifact/luckalot-sanook-api.zip
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiGateway

Outputs:
  ApiGatewayId:
    Description: Api Gateway Id
    Value: !Ref ApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayId"
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL for proxy function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/api"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"
  ProxyFunctionArn:
    Description: Proxy Function Arn
    Value: !GetAtt ProxyFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProxyFunctionArn"